/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALocaleProvider: typeof import('ant-design-vue/es')['LocaleProvider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CustomOrderModal: typeof import('./src/components/CustomOrderModal.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GLTFLogsModal: typeof import('./src/components/GLTFLogsModal.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LinkModal: typeof import('./src/components/LinkModal.vue')['default']
    LogDetail: typeof import('./src/components/LogDetail.vue')['default']
    ModelViewer: typeof import('./src/components/ModelViewer.vue')['default']
    Pay: typeof import('./src/components/Pay.vue')['default']
    PayInfo: typeof import('./src/components/PayInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SunSetting: typeof import('./src/components/SunSetting.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    ViewerTools: typeof import('./src/components/ViewerTools.vue')['default']
  }
}
